### ISSUE TITLE
Does DUC converge?

### ISSUE THREAD

**Issue by meijieru** [ycszen/pytorch-segmentation#5]
I try DUC on deeplab, but it produces unsatisfactory results.

**Comment by ycszen** [comment]
Yes. At least It can give me a just-so-so result.

**Comment by meijieru** [comment]
It seems that you utilize DUC at multiple position instead of the last one (as described in the paper). The difference may come from it. Though it may work, it introduces in-negligible parameters in addition (compared with de-convolution)

**Comment by ycszen** [comment]
I advise just use it at the last, because when I use it at multiple stage it give a confuse result.
